### ISSUE TITLE
Debug the failing unit tests.

### ISSUE THREAD

**Issue by deepesh-kn** [OpenST/compute#102]
The unit tests are randomly failing. 
Debug the logs and find the root cause. 

The failing unit tests are random. One of the failing logs is as follows.

```
1) Contract: Reputation::slash
       should fail if validator has already withdrawn:
     Error: 
Could not connect to your Ethereum client with the following parameters:
    - host       > localhost
    - port       > 8545
    - network_id > 1575884585089
Please check that your Ethereum client:
    - is running
    - is accepting RPC connections (i.e., "--rpc" option is used in geth)
    - is accessible over the network
    - is properly configured in your Truffle configuration file (truffle-config.js)
      at ProviderError.ExtendableError (node_modules/truffle/build/webpack:/packages/error/index.js:10:1)
      at new ProviderError (node_modules/truffle/build/webpack:/packages/provider/error.js:12:1)
      at /home/travis/build/mosaicdao/mosaic-1/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:75:1
      at /home/travis/build/mosaicdao/mosaic-1/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:107:1
      at XMLHttpRequest.request.onreadystatechange (node_modules/truffle/build/webpack:/~/web3-providers-http/src/index.js:102:1)
      at XMLHttpRequestEventTarget.dispatchEvent (node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)
      at XMLHttpRequest._setReadyState (node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:208:1)
      at XMLHttpRequest._onHttpRequestError (node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:349:1)
      at ClientRequest.<anonymous> (node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:252:47)
      at Socket.socketErrorListener (_http_client.js:401:9)
      at emitErrorNT (internal/streams/destroy.js:73:8)
      at _combinedTickCallback (internal/process/next_tick.js:139:11)
      at process._tickCallback (internal/process/next_tick.js:181:9)
  2) Contract: Reputation::stake
       should fail to stake validator pool if wETH token is not approved:
     
Could not connect to your Ethereum client with the following parameters:
    - host       > localhost
    - port       > 8545
    - network_id > 1575884585089
Please check that your Ethereum client:
    - is running
    - is accepting RPC connections (i.e., "--rpc" option is used in geth)
    - is accessible over the network
    - is properly configured in your Truffle configuration file (truffle-config.js)
  Error:     at PromiEvent (node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
      at TruffleContract.approve (node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:170:1)
      at Context.it (test/reputation/stake.js:190:16)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)
  3) Contract: Reputation::stake
       "after each" hook: after test for "should fail to stake validator pool if wETH token is not approved":
     Error: 
Could not connect to your Ethereum client with the following parameters:
    - host       > localhost
    - port       > 8545
    - network_id > 1575884585089
Please check that your Ethereum client:
    - is running
    - is accepting RPC connections (i.e., "--rpc" option is used in geth)
    - is accessible over the network
    - is properly configured in your Truffle configuration file (truffle-config.js)
      at ProviderError.ExtendableError (node_modules/truffle/build/webpack:/packages/error/index.js:10:1)
      at new ProviderError (node_modules/truffle/build/webpack:/packages/provider/error.js:12:1)
      at /home/travis/build/mosaicdao/mosaic-1/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:75:1
      at /home/travis/build/mosaicdao/mosaic-1/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:107:1
      at XMLHttpRequest.request.onreadystatechange (node_modules/truffle/build/webpack:/~/web3-providers-http/src/index.js:102:1)
      at XMLHttpRequestEventTarget.dispatchEvent (node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)
      at XMLHttpRequest._setReadyState (node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:208:1)
      at XMLHttpRequest._onHttpRequestError (node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:349:1)
      at ClientRequest.<anonymous> (node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:252:47)
      at Socket.socketErrorListener (_http_client.js:401:9)
      at emitErrorNT (internal/streams/destroy.js:73:8)
      at _combinedTickCallback (internal/process/next_tick.js:139:11)
      at process._tickCallback (internal/process/next_tick.js:181:9)
  4) Contract: Reputation::withdraw
       "before all" hook: prepare suite:
     Error: 
Could not connect to your Ethereum client with the following parameters:
    - host       > localhost
    - port       > 8545
    - network_id > 1575884585089
Please check that your Ethereum client:
    - is running
    - is accepting RPC connections (i.e., "--rpc" option is used in geth)
    - is accessible over the network
    - is properly configured in your Truffle configuration file (truffle-config.js)
      at ProviderError.ExtendableError (node_modules/truffle/build/webpack:/packages/error/index.js:10:1)
      at new ProviderError (node_modules/truffle/build/webpack:/packages/provider/error.js:12:1)
      at /home/travis/build/mosaicdao/mosaic-1/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:75:1
      at /home/travis/build/mosaicdao/mosaic-1/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:107:1
      at XMLHttpRequest.request.onreadystatechange (node_modules/truffle/build/webpack:/~/web3-providers-http/src/index.js:102:1)
      at XMLHttpRequestEventTarget.dispatchEvent (node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)
      at XMLHttpRequest._setReadyState (node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:208:1)
      at XMLHttpRequest._onHttpRequestError (node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:349:1)
      at ClientRequest.<anonymous> (node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:252:47)
      at Socket.socketErrorListener (_http_client.js:401:9)
      at emitErrorNT (internal/streams/destroy.js:73:8)
      at _combinedTickCallback (internal/process/next_tick.js:139:11)
      at process._tickCallback (internal/process/next_tick.js:181:9)


```

**Comment by abhayks1** [comment]
The ticket is implemented in PR: https://github.com/mosaicdao/mosaic-1/pull/105
