### ISSUE TITLE
Update web3 version to 1.2.4. 

### ISSUE THREAD

**Issue by 0xsarvesh** [OpenST/compute#29]
Updating web3 version causing failure in unit test cases. Update version and fix tests.

**Comment by 0xsarvesh** [comment]
```
  1) Contract: Committee::activateCommittee
       Contract: Positive Tests
         Checks storage state after successfull activation:
     Uncaught TypeError: callback is not a function
      at node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:112:1
      at XMLHttpRequest.request.onreadystatechange (node_modules/truffle/build/webpack:/~/web3-providers-http/src/index.js:91:1)
      at XMLHttpRequestEventTarget.dispatchEvent (node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)
      at XMLHttpRequest._setReadyState (node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:208:1)
      at XMLHttpRequest._onHttpResponseEnd (node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:318:1)
      at IncomingMessage.<anonymous> (node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:289:47)
      at endReadableNT (_stream_readable.js:1132:12)
      at processTicksAndRejections (internal/process/next_tick.js:76:17)
```
